FROM golang:1.21.1-alpine3.18 as dev

WORKDIR /work
COPY src ./
# COPY src/main.go ./
# COPY src/go.mod ./
# COPY src/go.sum ./
RUN go mod download
RUN go build -o app

FROM alpine:3 as prd
COPY --from=dev /work/app /
CMD ["/bin/sh", "-c", "/app"]