FROM golang:1.21.1-alpine3.18 as dev

WORKDIR /work

COPY src ./

RUN go mod download
RUN go build -o app

FROM alpine:3 as prd
COPY --from=dev /work/app /
RUN mkdir /cert
COPY --from=dev /work/cert /cert

CMD ["/bin/sh", "-c", "/app"]