### REST Client plug-in

### Insert Client
POST https://localhost:8081/cliente
ContentType: application/json

{
  "nome": "Marcio",
  "sobrenome": "Almeida",
  "contato": "Ale",
  "endereco": "Av. Presidente Vargas, 1",
  "dtNascimento": "10/07/1973",
  "cpf": "123.456.789-10"
}


### Insert Second Client
POST https://localhost:8081/cliente
ContentType: application/json

{
  "nome": "Alessandra",
  "sobrenome": "Nunes",
  "contato": "Marcio",
  "endereco": "Av. Rio Branco, 1",
  "dtNascimento": "26/09/1974",
  "cpf": "987.654.321-10"
}